version: '3'
services:
  eos:
    build: ./contract
    image: eosio
    container_name: eosio
    command: nodeos -e -p eosio --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --contracts-console --http-validate-host=false
    volumes:
      - ./contract/build:/work
      - ./contract/build/eosio/data:/mnt/dev/data
      - ./contract/build/eosio/config:/mnt/dev/config eosio/eos-dev
      - /data/db
    working_dir: /mnt/dev/data
    ports:
      - "8888:8888"
      - "9876:9876"
    networks:
      - dev

networks:
  dev:
    driver: bridge